name: lint

on:
    pull_request:
    push:
        branches:
            - master

jobs:
    lint_and_test:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python-version: ['3.10', '3.11', '3.12']
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: recursive
            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v4
                with:
                    python-version: ${{ matrix.python-version }}
            -   name: Set Variables
                id: set_variables
                shell: bash
                run: |
                    echo "PY=$(python -c 'import hashlib, sys;print(hashlib.sha256(sys.version.encode()+sys.executable.encode()).hexdigest())')" >> $GITHUB_OUTPUT
                    echo "PIP_CACHE=$(pip cache dir)" >> $GITHUB_OUTPUT
            -   name: Cache PIP
                uses: actions/cache@v3
                with:
                    path: ${{ steps.set_variables.outputs.PIP_CACHE }}
                    key: ${{ runner.os }}-pip-${{ steps.set_variables.outputs.PY }}
            -   name: Install dependencies
                run: |
                    python -m pip install --upgrade pip
                    pip install -r requirements.txt
                    pip install flake8
            -   name: Lint with flake8
                run:  |
                    # stop the build if there are Python syntax errors or undefined names
                    flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
                    # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
                    flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --per-file-ignores="paifulogger/log.py:C901,F401,F403,F405,E501 paifulogger/src/__init__.py:F401 test/test.py:E402" --exclude mjlog2mjai
            -   name: Test with test
                run: python -m unittest
